// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq-DYRUH_zopYsNUlesWT23Wm9CiK-HyA',
    appId: '1:462835304523:web:8eadb773d1ed69725de5ce',
    messagingSenderId: '462835304523',
    projectId: 'ousaapp-accc1',
    authDomain: 'ousaapp-accc1.firebaseapp.com',
    storageBucket: 'ousaapp-accc1.firebasestorage.app',
    measurementId: 'G-S9NTWFSLBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrBMjBzB7alfNUWG1nZ318Jebz29_HSA',
    appId: '1:462835304523:android:04c4aaa2ea6db8f35de5ce',
    messagingSenderId: '462835304523',
    projectId: 'ousaapp-accc1',
    storageBucket: 'ousaapp-accc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDplnE1BY0Hm0fybrIUmE3vjF8QkhS8WzM',
    appId: '1:462835304523:ios:0440b2316253d9995de5ce',
    messagingSenderId: '462835304523',
    projectId: 'ousaapp-accc1',
    storageBucket: 'ousaapp-accc1.firebasestorage.app',
    androidClientId: '462835304523-9b6uk7v1qsg1apjm1eov2iutmtbmi3dv.apps.googleusercontent.com',
    iosClientId: '462835304523-vb638mghvnjacubj3r3vo8udqksd1b2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ousaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDplnE1BY0Hm0fybrIUmE3vjF8QkhS8WzM',
    appId: '1:462835304523:ios:0440b2316253d9995de5ce',
    messagingSenderId: '462835304523',
    projectId: 'ousaapp-accc1',
    storageBucket: 'ousaapp-accc1.firebasestorage.app',
    androidClientId: '462835304523-9b6uk7v1qsg1apjm1eov2iutmtbmi3dv.apps.googleusercontent.com',
    iosClientId: '462835304523-vb638mghvnjacubj3r3vo8udqksd1b2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ousaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq-DYRUH_zopYsNUlesWT23Wm9CiK-HyA',
    appId: '1:462835304523:web:5c20741231cab7dd5de5ce',
    messagingSenderId: '462835304523',
    projectId: 'ousaapp-accc1',
    authDomain: 'ousaapp-accc1.firebaseapp.com',
    storageBucket: 'ousaapp-accc1.firebasestorage.app',
    measurementId: 'G-GY7RFVKNC4',
  );

}